In [1]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
data={
    'review':['Avg','Poor','Good','Good','Poor','Avg','Poor','Good'],
    'eductaion':['UG','School','PG','School','UG','PG','UG','School'],
    'Purchased':['Yes','No','Yes','No','Yes','No','No','Yes']
}

In [3]:
df=pd.DataFrame(data)

In [4]:
df.head()

review eductaion Purchased
0    Avg        UG       Yes
1   Poor    School        No
2   Good        PG       Yes
3   Good    School        No
4   Poor        UG       Yes


Ordinal Encoding

We apply OrdinalEncoding on those column who's value have some interdependencies

like column ['review'] & ['education'] where ['review'] has three values ['Avg','Poor','Good'] that should be Poor->Avg->Good
and ['education'] has three values ['UG','School','PG'] that should be School->UG->PG


LabelEncoding 

We are recommended to apply Label Encoding only on target column,

like column['Purchase'] in this case




In [5]:
X=df.drop('Purchased',axis=1)
y=df['Purchased']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [7]:
print(X_train.shape,y_train.shape)

(5, 2) (5,)


In [8]:
OE=OrdinalEncoder(categories=[['Poor','Avg','Good'],['School', 'UG', 'PG']])

In [9]:
OE.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Avg', 'Good'], ['School', 'UG', 'PG']])

In [10]:
X_train=OE.transform(X_train)
X_test=OE.transform(X_test)

In [11]:
X_test

array([[0., 0.],
       [1., 2.],
       [1., 1.]])

In [12]:
X_train

array([[2., 0.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [0., 1.]])

In [13]:




 #  Applying Label Encoder

Label=LabelEncoder()

Label.fit(y_train)


y_train=Label.transform(y_train)
y_test=Label.transform(y_test)

In [14]:
y_train

array([1, 1, 1, 0, 0])

As you can se we have successfully converted categorical dataset into numerical one

# 

# 

# 

# Avoiding the lengthy process Using ColumnTransformer

In [7]:
from sklearn.compose import ColumnTransformer

In [18]:
clf=ColumnTransformer(transformers=[
    ('tn1',OrdinalEncoder(categories=[['Poor','Avg','Good'],['School', 'UG', 'PG']]),[0,1]),
],remainder='passthrough')

In [19]:
clf.fit(X_train)

ColumnTransformer(remainder='passthrough',
                  transformers=[('tn1',
                                 OrdinalEncoder(categories=[['Poor', 'Avg',
                                                             'Good'],
                                                            ['School', 'UG',
                                                             'PG']]),
                                 [0, 1])])

In [20]:
clf.transform(X_train)

array([[2., 0.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [0., 1.]])

In [21]:
clf.transform(X_test)

array([[0., 0.],
       [1., 2.],
       [1., 1.]])